version: '3'
services:
  db:
    image: "postgres:11-alpine"
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    env_file:
      - ./ecommerce/.env
    networks:
      - db_nw
  app:
    build: .
    image: "jwdepetro/ecommerce"
    env_file:
      - ./ecommerce/.env
    volumes:
      - .:/opt/services/ecommerce/src
    networks:
      - db_nw
      - web_nw
    depends_on:
      - db
  nginx:
    image: "nginx:1-alpine"
    ports:
      - "8080:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./static:/static
    networks:
      - web_nw
    depends_on: 
      - app
networks:
  db_nw:
    driver: bridge
  web_nw:
    driver: bridge
volumes:
  dbdata: