# Generated by Django 2.1.2 on 2018-10-26 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='session_id',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
    ]
